apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-functions-pipeline
serialPipeline:
  stages:
    - targetId: sample-env
      strategy:
        canary:
          customCanaryDeployment:
            phaseConfigs:
              - phaseId: canary-25
                percentage: 25
              - phaseId: canary-50
                percentage: 50
              - phaseId: canary-75
                percentage: 75
              - phaseId: stable
                percentage: 100
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: sample-env
customTarget:
  customTargetType: cloud-run-functions
---
apiVersion: deploy.cloud.google.com/v1
kind: CustomTargetType
metadata:
  name: cloud-run-functions
customActions:
  renderAction: cloud-run-functions-renderer
  deployAction: cloud-run-functions-deployer
