apiVersion: skaffold/v4beta7
kind: Config
customActions:
  - name: cloud-run-functions-renderer
    containers:
      - name: render
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:503.0.0-stable
        command: ["/bin/bash"]
        args:
          - "-c"
          - |-
            echo {\"commit\": \"$CLOUD_DEPLOY_customTarget_commit\"} > manifest.json
            gcloud storage cp manifest.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.json

            echo {\"resultStatus\": \"SUCCEEDED\", \"manifestFile\": \"$CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.json\"} > results.json
            gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
  - name: cloud-run-functions-deployer
    containers:
      - name: deploy
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:503.0.0-stable
        command: ["/bin/bash"]
        args:
          - "-c"
          - |-
            if [ \"$CLOUD_DEPLOY_FEATURES\" = \"CANARY\" ] \
              && [ \"$CLOUD_DEPLOY_PERCENTAGE_DEPLOY\" -ne 100 ] \
              && ! gcloud functions describe go-http-function --region=asia-northeast1 > /dev/null 2>&1; then
              echo {\"resultStatus\": \"SKIPPED\"} > results.json
              gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
              exit 0
            fi

            apt-get update
            apt-get install -y git

            git clone https://github.com/YunosukeY/cloud-deploy-cloud-run-functions-sample.git
            cd cloud-deploy-cloud-run-functions-sample
            git checkout $CLOUD_DEPLOY_customTarget_commit

            gcloud beta run deploy go-http-function \
              --base-image go122 \
              --region asia-northeast1 \
              --source . \
              --function HelloGet \
              --no-allow-unauthenticated \
              --no-traffic
            gcloud run services update-traffic go-http-function \
              --region asia-northeast1 \
              --to-revisions=LATEST=$CLOUD_DEPLOY_PERCENTAGE_DEPLOY

            echo {\"resultStatus\": \"SUCCEEDED\"} > results.json
            gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
